// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scoreboard.Data.Context;

#nullable disable

namespace Scoreboard.Data.Migrations
{
    [DbContext(typeof(ScoreboardDbContext))]
    partial class ScoreboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scoreboard.Domain.Students.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Point")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Assessments", (string)null);
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Stream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Streams", (string)null);
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.StreamCourses", b =>
                {
                    b.Property<int>("StreamId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("StreamId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("StreamCourses", (string)null);
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StreamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StreamId");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.StudentAssesment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<float>("AchievedPoints")
                        .HasColumnType("real");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("StudentId", "AssessmentId");

                    b.HasIndex("AssessmentId");

                    b.ToTable("StudentAssesments", (string)null);
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.StudentTotalPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("PercentageScore")
                        .HasColumnType("real");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<float>("TotalAchievedPoints")
                        .HasColumnType("real");

                    b.Property<float>("TotalPoints")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("StudentTotalPoints", (string)null);
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Assessment", b =>
                {
                    b.HasOne("Scoreboard.Domain.Students.Course", "Course")
                        .WithMany("Assesments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.StreamCourses", b =>
                {
                    b.HasOne("Scoreboard.Domain.Students.Course", "Course")
                        .WithMany("Streams")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scoreboard.Domain.Students.Stream", "Stream")
                        .WithMany("StreamCourses")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Student", b =>
                {
                    b.HasOne("Scoreboard.Domain.Students.Stream", "Stream")
                        .WithMany("Students")
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stream");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.StudentAssesment", b =>
                {
                    b.HasOne("Scoreboard.Domain.Students.Assessment", "Assessment")
                        .WithMany("Students")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scoreboard.Domain.Students.Student", "Student")
                        .WithMany("StudentAssesments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.StudentTotalPoint", b =>
                {
                    b.HasOne("Scoreboard.Domain.Students.Student", "Student")
                        .WithOne("StudentTotalPoint")
                        .HasForeignKey("Scoreboard.Domain.Students.StudentTotalPoint", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Assessment", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Course", b =>
                {
                    b.Navigation("Assesments");

                    b.Navigation("Streams");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Stream", b =>
                {
                    b.Navigation("StreamCourses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Scoreboard.Domain.Students.Student", b =>
                {
                    b.Navigation("StudentAssesments");

                    b.Navigation("StudentTotalPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
